apiVersion: v1
kind: Service
metadata:
  name: pitflow-orchestrator
  namespace: pitflow
spec:
  selector:
    app.kubernetes.io/name: pitflow-orchestrator
  ports:
    - name: http
      port: 80
      targetPort: 8080
